version: '3.9'

services:
  postgres:
    image: "postgres"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${PROSTGRES_DB}
      POSTGRES_USER: ${PROSTGRES_USER}
      POSTGRES_PASSWORD: ${PROSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
